/*
 * DNet eBusiness Suite
 * Copyright: 2008-2012 Nan21 Electronics SRL. All rights reserved.
 * Use is subject to license terms.
 */
Ext.define("net.nan21.dnet.module.sd.opportunity.ds.model.OpportunityDs" ,{
	extend: 'Ext.data.Model',
	fields: [
		{name:"account", type:"string"},
		{name:"accountId", type:"int", useNull:true},
		{name:"active", type:"boolean"},
		{name:"amount", type:"float", useNull:true},
		{name:"assignedTo", type:"string"},
		{name:"assignedToId", type:"int", useNull:true},
		{name:"businessObject", type:"string"},
		{name:"campaign", type:"string"},
		{name:"className", type:"string"},
		{name:"clientId", type:"int", useNull:true},
		{name:"closeDate", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdAt", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdBy", type:"string"},
		{name:"currency", type:"string"},
		{name:"currencyId", type:"int", useNull:true},
		{name:"description", type:"string"},
		{name:"entityFQN", type:"string"},
		{name:"id", type:"int", useNull:true},
		{name:"leadSource", type:"string"},
		{name:"leadSourceId", type:"int", useNull:true},
		{name:"modifiedAt", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"modifiedBy", type:"string"},
		{name:"name", type:"string"},
		{name:"priority", type:"string"},
		{name:"priorityId", type:"int", useNull:true},
		{name:"probability", type:"float", useNull:true},
		{name:"resultNote", type:"string"},
		{name:"resultReason", type:"string"},
		{name:"resultReasonId", type:"int", useNull:true},
		{name:"salesStage", type:"string"},
		{name:"salesStageId", type:"int", useNull:true},
		{name:"status", type:"string"},
		{name:"statusId", type:"int", useNull:true},
		{name:"uuid", type:"string"},
		{name:"version", type:"int", useNull:true}
	],
	validations: [
		{field: "name", type: 'presence'}
	]
});
Ext.define("net.nan21.dnet.module.sd.opportunity.ds.model.OpportunityDsFilter" ,{
	extend: 'Ext.data.Model',
	fields: [
		{name:"account", type:"string"},
		{name:"accountId", type:"int", useNull:true},
		{name:"accountId_From",type:"int", useNull:true},
		{name:"accountId_To",type:"int", useNull:true},
		{name:"active", type:"boolean", useNull:true},
		{name:"amount", type:"float", useNull:true},
		{name:"amount_From",type:"float", useNull:true},
		{name:"amount_To",type:"float", useNull:true},
		{name:"assignedTo", type:"string"},
		{name:"assignedToId", type:"int", useNull:true},
		{name:"assignedToId_From",type:"int", useNull:true},
		{name:"assignedToId_To",type:"int", useNull:true},
		{name:"businessObject", type:"string"},
		{name:"campaign", type:"string"},
		{name:"className", type:"string"},
		{name:"closeDate", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"closeDate_From",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"closeDate_To",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdAt", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdAt_From",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdAt_To",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdBy", type:"string"},
		{name:"currency", type:"string"},
		{name:"currencyId", type:"int", useNull:true},
		{name:"currencyId_From",type:"int", useNull:true},
		{name:"currencyId_To",type:"int", useNull:true},
		{name:"description", type:"string"},
		{name:"entityFQN", type:"string"},
		{name:"id", type:"int", useNull:true},
		{name:"leadSource", type:"string"},
		{name:"leadSourceId", type:"int", useNull:true},
		{name:"leadSourceId_From",type:"int", useNull:true},
		{name:"leadSourceId_To",type:"int", useNull:true},
		{name:"modifiedAt", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"modifiedAt_From",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"modifiedAt_To",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"modifiedBy", type:"string"},
		{name:"name", type:"string"},
		{name:"priority", type:"string"},
		{name:"priorityId", type:"int", useNull:true},
		{name:"priorityId_From",type:"int", useNull:true},
		{name:"priorityId_To",type:"int", useNull:true},
		{name:"probability", type:"float", useNull:true},
		{name:"probability_From",type:"float", useNull:true},
		{name:"probability_To",type:"float", useNull:true},
		{name:"resultNote", type:"string"},
		{name:"resultReason", type:"string"},
		{name:"resultReasonId", type:"int", useNull:true},
		{name:"resultReasonId_From",type:"int", useNull:true},
		{name:"resultReasonId_To",type:"int", useNull:true},
		{name:"salesStage", type:"string"},
		{name:"salesStageId", type:"int", useNull:true},
		{name:"salesStageId_From",type:"int", useNull:true},
		{name:"salesStageId_To",type:"int", useNull:true},
		{name:"status", type:"string"},
		{name:"statusId", type:"int", useNull:true},
		{name:"statusId_From",type:"int", useNull:true},
		{name:"statusId_To",type:"int", useNull:true},
		{name:"uuid", type:"string"}
	]
});
Ext.define("net.nan21.dnet.module.sd.opportunity.ds.param.OpportunityDsParam", {
	extend: 'Ext.data.Model',
	fields: [ 
	]
});
